/**
 * Auto-generated Supabase database types.
 *
 * Regenerate with:
 *   npm run supabase:types
 *
 * Do NOT edit this file manually — updated via `supabase gen types typescript`.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string;
          nome: string;
          sku: string | null;
          categoria_id: string | null;
          descricao: string | null;
          unidade: string | null;
          estoque: number;
          min_estoque: number | null;
          ativo: boolean;
          created_at: string;
          updated_at: string;
          // Estoque app columns
          sku_interno: string | null;
          codigo_origem: string | null;
          nome_original: string | null;
          nome_padronizado: string | null;
          marca: string | null;
          linha: string | null;
          variacao: string | null;
          volume: string | null;
          custo: number | null;
          preco_venda: number | null;
          tray_product_id: string | null;
          imagem_url: string | null;
          metadata: Json;
        };
        Insert: {
          id?: string;
          nome: string;
          sku?: string | null;
          categoria_id?: string | null;
          descricao?: string | null;
          unidade?: string | null;
          estoque?: number;
          min_estoque?: number | null;
          ativo?: boolean;
          created_at?: string;
          updated_at?: string;
          sku_interno?: string | null;
          codigo_origem?: string | null;
          nome_original?: string | null;
          nome_padronizado?: string | null;
          marca?: string | null;
          linha?: string | null;
          variacao?: string | null;
          volume?: string | null;
          custo?: number | null;
          preco_venda?: number | null;
          tray_product_id?: string | null;
          imagem_url?: string | null;
          metadata?: Json;
        };
        Update: {
          id?: string;
          nome?: string;
          sku?: string | null;
          categoria_id?: string | null;
          descricao?: string | null;
          unidade?: string | null;
          estoque?: number;
          min_estoque?: number | null;
          ativo?: boolean;
          updated_at?: string;
          sku_interno?: string | null;
          codigo_origem?: string | null;
          nome_original?: string | null;
          nome_padronizado?: string | null;
          marca?: string | null;
          linha?: string | null;
          variacao?: string | null;
          volume?: string | null;
          custo?: number | null;
          preco_venda?: number | null;
          tray_product_id?: string | null;
          imagem_url?: string | null;
          metadata?: Json;
        };
      };
      import_jobs: {
        Row: {
          id: string;
          nome_arquivo: string;
          tipo_arquivo: "csv" | "excel" | "pdf";
          storage_path: string | null;
          status: "pendente" | "processando" | "concluido" | "erro";
          total_itens: number;
          itens_aprovados: number;
          itens_bloqueados: number;
          itens_erro: number;
          erro_mensagem: string | null;
          iniciado_em: string | null;
          concluido_em: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nome_arquivo: string;
          tipo_arquivo: "csv" | "excel" | "pdf";
          storage_path?: string | null;
          status?: "pendente" | "processando" | "concluido" | "erro";
          total_itens?: number;
          itens_aprovados?: number;
          itens_bloqueados?: number;
          itens_erro?: number;
          erro_mensagem?: string | null;
          iniciado_em?: string | null;
          concluido_em?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nome_arquivo?: string;
          tipo_arquivo?: "csv" | "excel" | "pdf";
          storage_path?: string | null;
          status?: "pendente" | "processando" | "concluido" | "erro";
          total_itens?: number;
          itens_aprovados?: number;
          itens_bloqueados?: number;
          itens_erro?: number;
          erro_mensagem?: string | null;
          iniciado_em?: string | null;
          concluido_em?: string | null;
          updated_at?: string;
        };
      };
      import_job_items: {
        Row: {
          id: string;
          import_job_id: string;
          linha_original: Json;
          numero_linha: number | null;
          sku_interno: string | null;
          codigo_origem: string | null;
          nome_original: string | null;
          nome_padronizado: string | null;
          marca: string | null;
          linha: string | null;
          variacao: string | null;
          volume: string | null;
          estoque: number | null;
          custo: number | null;
          preco_venda: number | null;
          status_processamento: "pendente" | "processando" | "aprovado_automaticamente" | "bloqueado_por_duvida" | "erro_tecnico" | "sincronizado_tray";
          score_duplicidade: number;
          motivo_bloqueio: string | null;
          produto_id: string | null;
          tray_product_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          import_job_id: string;
          linha_original?: Json;
          numero_linha?: number | null;
          sku_interno?: string | null;
          codigo_origem?: string | null;
          nome_original?: string | null;
          nome_padronizado?: string | null;
          marca?: string | null;
          linha?: string | null;
          variacao?: string | null;
          volume?: string | null;
          estoque?: number | null;
          custo?: number | null;
          preco_venda?: number | null;
          status_processamento?: "pendente" | "processando" | "aprovado_automaticamente" | "bloqueado_por_duvida" | "erro_tecnico" | "sincronizado_tray";
          score_duplicidade?: number;
          motivo_bloqueio?: string | null;
          produto_id?: string | null;
          tray_product_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          import_job_id?: string;
          linha_original?: Json;
          numero_linha?: number | null;
          sku_interno?: string | null;
          codigo_origem?: string | null;
          nome_original?: string | null;
          nome_padronizado?: string | null;
          marca?: string | null;
          linha?: string | null;
          variacao?: string | null;
          volume?: string | null;
          estoque?: number | null;
          custo?: number | null;
          preco_venda?: number | null;
          status_processamento?: "pendente" | "processando" | "aprovado_automaticamente" | "bloqueado_por_duvida" | "erro_tecnico" | "sincronizado_tray";
          score_duplicidade?: number;
          motivo_bloqueio?: string | null;
          produto_id?: string | null;
          tray_product_id?: string | null;
          updated_at?: string;
        };
      };
      supplier_items: {
        Row: {
          id: string;
          import_job_item_id: string | null;
          product_id: string | null;
          sku_interno: string | null;
          codigo_origem: string | null;
          nome_original: string;
          nome_padronizado: string;
          marca: string | null;
          variacao: string | null;
          volume: string | null;
          estoque: number;
          custo: number | null;
          preco_venda: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          import_job_item_id?: string | null;
          product_id?: string | null;
          sku_interno?: string | null;
          codigo_origem?: string | null;
          nome_original: string;
          nome_padronizado: string;
          marca?: string | null;
          variacao?: string | null;
          volume?: string | null;
          estoque?: number;
          custo?: number | null;
          preco_venda?: number | null;
          created_at?: string;
        };
        Update: {
          import_job_item_id?: string | null;
          product_id?: string | null;
          sku_interno?: string | null;
          codigo_origem?: string | null;
          nome_original?: string;
          nome_padronizado?: string;
          marca?: string | null;
          variacao?: string | null;
          volume?: string | null;
          estoque?: number;
          custo?: number | null;
          preco_venda?: number | null;
        };
      };
      duplicate_checks: {
        Row: {
          id: string;
          import_job_item_id: string;
          produto_candidato_id: string | null;
          score: number;
          motivo: string;
          detalhes: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          import_job_item_id: string;
          produto_candidato_id?: string | null;
          score: number;
          motivo: string;
          detalhes?: Json;
          created_at?: string;
        };
        Update: {
          score?: number;
          motivo?: string;
          detalhes?: Json;
        };
      };
      tray_sync_logs: {
        Row: {
          id: string;
          import_job_item_id: string | null;
          product_id: string | null;
          acao: "criar" | "atualizar" | "erro";
          tray_product_id: string | null;
          request_payload: Json | null;
          response_payload: Json | null;
          status_code: number | null;
          erro_mensagem: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          import_job_item_id?: string | null;
          product_id?: string | null;
          acao: "criar" | "atualizar" | "erro";
          tray_product_id?: string | null;
          request_payload?: Json | null;
          response_payload?: Json | null;
          status_code?: number | null;
          erro_mensagem?: string | null;
          created_at?: string;
        };
        Update: {
          acao?: "criar" | "atualizar" | "erro";
          tray_product_id?: string | null;
          request_payload?: Json | null;
          response_payload?: Json | null;
          status_code?: number | null;
          erro_mensagem?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
